import type { Influencer } from './types';

export const mockInfluencers: Influencer[] = [
  // ===== YouTube AI 达人 =====
  {
    id: 'yt_001', platform: 'youtube', username: 'MattVidPro', displayName: 'Matt Wolfe',
    followers: 1500000, avgViews: 180000, postFreq: 8,
    email: 'matt@mattwolfe.com', otherContacts: ['@mreflow (Twitter)', 'mattwolfe.ai'],
    bio: 'AI tools, news & tutorials. I explore the latest in AI video, image, and productivity tools.', verified: false,
    tags: ['ai', 'ai video', 'ai tools', 'generative ai'],
    profileUrl: 'https://www.youtube.com/@mreflow',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MattWolfe',
  },
  {
    id: 'yt_002', platform: 'youtube', username: 'aiexplained-official', displayName: 'AI Explained',
    followers: 820000, avgViews: 320000, postFreq: 6,
    email: '', otherContacts: ['@aiaboratorio (Twitter)'],
    bio: 'Explaining AI concepts, new models, and breakthroughs in an accessible way.', verified: false,
    tags: ['ai', 'ai explained', 'machine learning', 'deep learning'],
    profileUrl: 'https://www.youtube.com/@aiaboratorio',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AIExplained',
  },
  {
    id: 'yt_003', platform: 'youtube', username: 'andrej_karpathy', displayName: 'Andrej Karpathy',
    followers: 810000, avgViews: 450000, postFreq: 2,
    email: '', otherContacts: ['@karpathy (Twitter)', 'karpathy.ai'],
    bio: 'Building Eureka Labs. Previously Director of AI at Tesla. Ex-OpenAI founding team. Neural networks, AI.', verified: true,
    tags: ['ai', 'deep learning', 'neural networks', 'machine learning'],
    profileUrl: 'https://www.youtube.com/@AndrejKarpathy',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Karpathy',
  },
  {
    id: 'yt_004', platform: 'youtube', username: 'AllAboutAI', displayName: 'All About AI',
    followers: 720000, avgViews: 95000, postFreq: 12,
    email: '', otherContacts: ['@allaboutai (Twitter)'],
    bio: 'Daily AI news, AI video generation, AI image generation tutorials and reviews.', verified: false,
    tags: ['ai', 'ai video', 'ai image', 'ai tools', 'generative ai'],
    profileUrl: 'https://www.youtube.com/@AllAboutAI',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AllAboutAI',
  },
  {
    id: 'yt_005', platform: 'youtube', username: 'codewithyu', displayName: 'CodeWithYu',
    followers: 430000, avgViews: 55000, postFreq: 10,
    email: '', otherContacts: ['@codewithyu (Twitter)'],
    bio: 'AI coding assistants, GPT tutorials, and building AI-powered applications.', verified: false,
    tags: ['ai', 'ai coding', 'gpt', 'programming'],
    profileUrl: 'https://www.youtube.com/@CodeWithYu',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=CodeWithYu',
  },
  {
    id: 'yt_006', platform: 'youtube', username: 'RobertRodriguezAI', displayName: 'Robert Rodriguez (AI Art)',
    followers: 310000, avgViews: 42000, postFreq: 8,
    email: 'robert@aivideoart.com', otherContacts: ['@robertrodriguez_ai (Twitter)'],
    bio: 'Creating stunning AI-generated videos and art. Tutorials on Runway, Pika, Sora, Midjourney.', verified: false,
    tags: ['ai video', 'ai art', 'ai image', 'runway', 'midjourney', 'generative ai'],
    profileUrl: 'https://www.youtube.com/@RobertRodriguezAI',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RobRodAI',
  },
  {
    id: 'yt_007', platform: 'youtube', username: 'Fireship', displayName: 'Fireship',
    followers: 3200000, avgViews: 1200000, postFreq: 7,
    email: '', otherContacts: ['@fireship_dev (Twitter)', 'fireship.io'],
    bio: 'High-intensity ⚡ code tutorials and mass tech explainers to help you ship your app faster.', verified: true,
    tags: ['ai', 'programming', 'web dev', 'technology'],
    profileUrl: 'https://www.youtube.com/@Fireship',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fireship',
  },
  {
    id: 'yt_008', platform: 'youtube', username: 'ai-for-everyone', displayName: 'AI For Everyone',
    followers: 260000, avgViews: 38000, postFreq: 10,
    email: '', otherContacts: [],
    bio: 'AI tools for everyday people. AI video, AI writing, AI image generation made simple.', verified: false,
    tags: ['ai', 'ai tools', 'ai video', 'ai image', 'chatgpt'],
    profileUrl: 'https://www.youtube.com/@ai-for-everyone',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AIForeveryone',
  },
  {
    id: 'yt_009', platform: 'youtube', username: 'AIJason', displayName: 'AI Jason',
    followers: 380000, avgViews: 68000, postFreq: 9,
    email: '', otherContacts: ['@aiaboratorio2 (Twitter)', 'aiproductivity.com'],
    bio: 'AI productivity tools, ChatGPT tips, AI workflow automation for creators and businesses.', verified: false,
    tags: ['ai', 'ai productivity', 'chatgpt', 'ai tools', 'automation'],
    profileUrl: 'https://www.youtube.com/@AIJason',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AIJason',
  },
  {
    id: 'yt_010', platform: 'youtube', username: 'NolanMoviesAI', displayName: 'Nolan (AI Filmmaker)',
    followers: 190000, avgViews: 120000, postFreq: 5,
    email: 'nolan@aifilmmaker.com', otherContacts: ['@nolanfilmsai (Twitter)'],
    bio: 'Making entire movies using AI. Runway ML, Sora, Stable Diffusion for filmmaking.', verified: false,
    tags: ['ai video', 'ai filmmaking', 'runway', 'sora', 'ai art'],
    profileUrl: 'https://www.youtube.com/@NolanMoviesAI',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=NolanAI',
  },
  {
    id: 'yt_011', platform: 'youtube', username: 'AI_Video_Creator', displayName: 'AI Video Creator',
    followers: 145000, avgViews: 28000, postFreq: 12,
    email: '', otherContacts: [],
    bio: 'Step-by-step tutorials on creating AI-generated videos using Kling, Runway, Pika, and Haiper.', verified: false,
    tags: ['ai video', 'kling', 'runway', 'pika', 'haiper', 'text to video'],
    profileUrl: 'https://www.youtube.com/@AI_Video_Creator',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AIVideoCreator',
  },
  {
    id: 'yt_012', platform: 'youtube', username: 'LatentSpaceAI', displayName: 'Latent Space',
    followers: 120000, avgViews: 45000, postFreq: 4,
    email: '', otherContacts: ['@latentspacepod (Twitter)', 'latentspacepod.com'],
    bio: 'The podcast for AI engineers. Covering LLMs, AI infrastructure, and the future of machine learning.', verified: false,
    tags: ['ai', 'llm', 'machine learning', 'podcast'],
    profileUrl: 'https://www.youtube.com/@LatentSpaceAI',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LatentSpace',
  },
  {
    id: 'yt_013', platform: 'youtube', username: 'ExplainThisAI', displayName: 'Explain This AI',
    followers: 95000, avgViews: 52000, postFreq: 6,
    email: '', otherContacts: [],
    bio: 'Breaking down complex AI topics. From GPT to Midjourney to Sora — explained simply.', verified: false,
    tags: ['ai', 'ai explained', 'ai video', 'ai image', 'gpt'],
    profileUrl: 'https://www.youtube.com/@ExplainThisAI',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ExplainThisAI',
  },
  {
    id: 'yt_014', platform: 'youtube', username: 'AIAndrew', displayName: 'AI Andrew',
    followers: 175000, avgViews: 35000, postFreq: 8,
    email: '', otherContacts: ['@aiandrew (Twitter)'],
    bio: 'AI image generation tutorials: Stable Diffusion, ComfyUI, Midjourney, DALL-E workflows.', verified: false,
    tags: ['ai image', 'stable diffusion', 'comfyui', 'midjourney', 'ai art'],
    profileUrl: 'https://www.youtube.com/@AIAndrew',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AIAndrew',
  },
  {
    id: 'yt_015', platform: 'youtube', username: 'runwayml', displayName: 'Runway',
    followers: 250000, avgViews: 85000, postFreq: 6,
    email: 'press@runwayml.com', otherContacts: ['@runwayml (Twitter)', 'runwayml.com'],
    bio: 'Runway is an applied AI research company shaping the next era of art, entertainment and human creativity.', verified: true,
    tags: ['ai video', 'runway', 'gen-3', 'text to video', 'ai filmmaking'],
    profileUrl: 'https://www.youtube.com/@runwayml',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RunwayML',
  },

  // ===== Instagram AI 达人 =====
  {
    id: 'ig_001', platform: 'instagram', username: 'ai.for.everyone', displayName: 'AI For Everyone',
    followers: 1850000, avgViews: 320000, postFreq: 18,
    email: 'hello@aiforeveryone.co', otherContacts: ['@aiforeveryone (Twitter)', 'aiforeveryone.co'],
    bio: 'Daily AI tools & news to boost your productivity ✨ AI video | AI art | ChatGPT tips', verified: false,
    tags: ['ai', 'ai tools', 'ai video', 'ai art', 'productivity'],
    profileUrl: 'https://www.instagram.com/ai.for.everyone/',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ig_aiforeveryone',
  },
  {
    id: 'ig_002', platform: 'instagram', username: 'the.ai.hub', displayName: 'The AI Hub',
    followers: 2400000, avgViews: 580000, postFreq: 22,
    email: 'partnerships@theaihub.co', otherContacts: ['@theaihub (Twitter)'],
    bio: 'The latest AI tools & news. We make AI accessible for everyone. 🤖✨', verified: false,
    tags: ['ai', 'ai tools', 'ai news', 'generative ai', 'chatgpt'],
    profileUrl: 'https://www.instagram.com/the.ai.hub/',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ig_theaihub',
  },
  {
    id: 'ig_003', platform: 'instagram', username: 'ai_generated_art_daily', displayName: 'AI Art Daily',
    followers: 980000, avgViews: 180000, postFreq: 14,
    email: '', otherContacts: [],
    bio: 'Beautiful AI-generated art every day. Created with Midjourney, DALL-E & Stable Diffusion 🎨', verified: false,
    tags: ['ai art', 'ai image', 'midjourney', 'stable diffusion', 'ai generated'],
    profileUrl: 'https://www.instagram.com/ai_generated_art_daily/',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ig_aiartdaily',
  },
  {
    id: 'ig_004', platform: 'instagram', username: 'ai.videos.trends', displayName: 'AI Videos & Trends',
    followers: 650000, avgViews: 95000, postFreq: 16,
    email: 'collab@aivideostrends.com', otherContacts: [],
    bio: 'Mind-blowing AI videos daily. Runway, Pika, Kling, Sora and more 🎬🤖', verified: false,
    tags: ['ai video', 'runway', 'pika', 'kling', 'sora', 'text to video'],
    profileUrl: 'https://www.instagram.com/ai.videos.trends/',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ig_aivideos',
  },
  {
    id: 'ig_005', platform: 'instagram', username: 'stability.ai', displayName: 'Stability AI',
    followers: 520000, avgViews: 120000, postFreq: 8,
    email: 'press@stability.ai', otherContacts: ['@stabilityai (Twitter)', 'stability.ai'],
    bio: 'The official Stability AI account. Building open AI tools. Stable Diffusion, Stable Video, and more.', verified: true,
    tags: ['ai', 'stable diffusion', 'ai image', 'ai video', 'open source'],
    profileUrl: 'https://www.instagram.com/stability.ai/',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ig_stabilityai',
  },
  {
    id: 'ig_006', platform: 'instagram', username: 'midjourney_official_fan', displayName: 'Midjourney Showcase',
    followers: 780000, avgViews: 150000, postFreq: 12,
    email: '', otherContacts: [],
    bio: 'Best Midjourney creations & prompts. Learn AI image generation 🖼️✨', verified: false,
    tags: ['ai art', 'midjourney', 'ai image', 'prompts'],
    profileUrl: 'https://www.instagram.com/midjourney_official_fan/',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ig_midjourney',
  },
  {
    id: 'ig_007', platform: 'instagram', username: 'ai.design.studio', displayName: 'AI Design Studio',
    followers: 420000, avgViews: 72000, postFreq: 10,
    email: 'hello@aidesignstudio.co', otherContacts: [],
    bio: 'AI-powered design inspiration. Logo design, UI/UX, brand identity with AI tools 🎨💻', verified: false,
    tags: ['ai', 'ai design', 'ai image', 'logo design', 'ui ux'],
    profileUrl: 'https://www.instagram.com/ai.design.studio/',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ig_aidesignstudio',
  },
  {
    id: 'ig_008', platform: 'instagram', username: 'chatgpt.prompts', displayName: 'ChatGPT Prompts Hub',
    followers: 1100000, avgViews: 250000, postFreq: 20,
    email: '', otherContacts: ['@gptprompts (Twitter)'],
    bio: 'Best ChatGPT prompts daily. Boost your productivity with AI 🧠⚡', verified: false,
    tags: ['ai', 'chatgpt', 'prompts', 'ai productivity'],
    profileUrl: 'https://www.instagram.com/chatgpt.prompts/',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ig_chatgptprompts',
  },
  {
    id: 'ig_009', platform: 'instagram', username: 'kling_ai_videos', displayName: 'Kling AI Videos',
    followers: 310000, avgViews: 55000, postFreq: 10,
    email: '', otherContacts: [],
    bio: 'Incredible AI videos made with Kling AI. Text-to-video & image-to-video examples 🎬🇨🇳', verified: false,
    tags: ['ai video', 'kling', 'text to video', 'ai generated video'],
    profileUrl: 'https://www.instagram.com/kling_ai_videos/',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ig_klingai',
  },
  {
    id: 'ig_010', platform: 'instagram', username: 'aiphoto.edit', displayName: 'AI Photo Edit',
    followers: 890000, avgViews: 160000, postFreq: 15,
    email: '', otherContacts: [],
    bio: 'AI photo editing tutorials & before/after reveals. Photoshop AI, Photoroom, Remove.bg and more 📸', verified: false,
    tags: ['ai', 'ai photo', 'ai image', 'photo editing', 'ai tools'],
    profileUrl: 'https://www.instagram.com/aiphoto.edit/',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ig_aiphotoedit',
  },
  {
    id: 'ig_011', platform: 'instagram', username: 'ai_startup_news', displayName: 'AI Startup News',
    followers: 370000, avgViews: 65000, postFreq: 12,
    email: 'news@aistartupdaily.com', otherContacts: ['@aistartupdaily (Twitter)'],
    bio: 'Daily AI startup funding, product launches, and industry insights 📈🤖', verified: false,
    tags: ['ai', 'startups', 'ai news', 'technology'],
    profileUrl: 'https://www.instagram.com/ai_startup_news/',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ig_aistartupnews',
  },
  {
    id: 'ig_012', platform: 'instagram', username: 'ai_music_creation', displayName: 'AI Music Lab',
    followers: 280000, avgViews: 48000, postFreq: 8,
    email: '', otherContacts: [],
    bio: 'Music created entirely by AI. Suno, Udio, and AI music tools 🎵🤖', verified: false,
    tags: ['ai', 'ai music', 'suno', 'udio', 'ai generated music'],
    profileUrl: 'https://www.instagram.com/ai_music_creation/',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ig_aimusic',
  },

  // ===== X (Twitter) AI 达人 =====
  {
    id: 'x_001', platform: 'x', username: 'sama', displayName: 'Sam Altman',
    followers: 3500000, avgViews: 4200000, postFreq: 18,
    email: 'press@openai.com', otherContacts: ['openai.com', 'blog.samaltman.com'],
    bio: 'CEO of OpenAI. Working on AGI.', verified: true,
    tags: ['ai', 'openai', 'gpt', 'agi', 'startups'],
    profileUrl: 'https://x.com/sama',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sama',
  },
  {
    id: 'x_002', platform: 'x', username: 'AndrewYNg', displayName: 'Andrew Ng',
    followers: 2400000, avgViews: 1800000, postFreq: 12,
    email: '', otherContacts: ['deeplearning.ai', 'coursera.com/andrewng'],
    bio: 'AI educator, founder of DeepLearning.AI, co-founder of Coursera. Making AI accessible to everyone.', verified: true,
    tags: ['ai', 'machine learning', 'deep learning', 'education'],
    profileUrl: 'https://x.com/AndrewYNg',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AndrewNg',
  },
  {
    id: 'x_003', platform: 'x', username: 'elonmusk', displayName: 'Elon Musk',
    followers: 200000000, avgViews: 35000000, postFreq: 100,
    email: '', otherContacts: ['xAI', 'Tesla', 'SpaceX'],
    bio: 'CEO of Tesla, SpaceX, xAI. Building Grok.', verified: true,
    tags: ['ai', 'xai', 'grok', 'technology', 'business'],
    profileUrl: 'https://x.com/elonmusk',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elonmusk',
  },
  {
    id: 'x_004', platform: 'x', username: '_aborohenbour', displayName: 'aboroHen Bour AI',
    followers: 850000, avgViews: 620000, postFreq: 25,
    email: '', otherContacts: [],
    bio: 'AI news & tools curator. Daily AI video/image generation demos and tutorials.', verified: false,
    tags: ['ai', 'ai video', 'ai image', 'ai tools', 'generative ai'],
    profileUrl: 'https://x.com/_aborohenbourAI',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aborohenbourAI',
  },
  {
    id: 'x_005', platform: 'x', username: 'aboroVideoAI', displayName: 'aboro Video AI',
    followers: 520000, avgViews: 380000, postFreq: 18,
    email: '', otherContacts: [],
    bio: 'AI video generation expert. Showcasing Sora, Runway, Kling & Pika creations daily.', verified: false,
    tags: ['ai video', 'sora', 'runway', 'kling', 'pika'],
    profileUrl: 'https://x.com/aboroVideoAI',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aboroVideoAI',
  },
  {
    id: 'x_006', platform: 'x', username: 'aboroArtDaily', displayName: 'aboro Art Daily',
    followers: 340000, avgViews: 280000, postFreq: 20,
    email: '', otherContacts: [],
    bio: 'Curating the best AI-generated art. Midjourney, Stable Diffusion, DALL-E masterpieces.', verified: false,
    tags: ['ai art', 'ai image', 'midjourney', 'stable diffusion', 'ai generated'],
    profileUrl: 'https://x.com/aboroArtDaily',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aboroArtDaily',
  },
  {
    id: 'x_007', platform: 'x', username: 'aboroAIToolsDaily', displayName: 'AI Tools Daily',
    followers: 680000, avgViews: 450000, postFreq: 22,
    email: 'collab@aitoolsdaily.com', otherContacts: ['aitoolsdaily.com'],
    bio: 'Daily AI tools discoveries. ChatGPT, Claude, Midjourney, Runway — tested and reviewed.', verified: false,
    tags: ['ai tools', 'chatgpt', 'midjourney', 'ai productivity'],
    profileUrl: 'https://x.com/aboroAIToolsDaily',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AIToolsDaily',
  },
  {
    id: 'x_008', platform: 'x', username: 'aboroAI_News', displayName: 'AI News Now',
    followers: 410000, avgViews: 310000, postFreq: 15,
    email: '', otherContacts: [],
    bio: 'Breaking AI news. Model releases, funding rounds, industry analysis.', verified: false,
    tags: ['ai', 'ai news', 'machine learning', 'technology'],
    profileUrl: 'https://x.com/aboroAI_News',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aboroAINews',
  },
  {
    id: 'x_009', platform: 'x', username: 'aboroFilmmaker', displayName: 'AI Filmmaker',
    followers: 290000, avgViews: 220000, postFreq: 16,
    email: '', otherContacts: [],
    bio: 'AI filmmaking & video generation. Exploring the creative possibilities of AI video tools.', verified: false,
    tags: ['ai video', 'ai filmmaking', 'runway', 'sora', 'gen-3'],
    profileUrl: 'https://x.com/aboroFilmmaker',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aboroFilmmaker',
  },
  {
    id: 'x_010', platform: 'x', username: 'aboroArtCurator', displayName: 'AI Art Curator',
    followers: 520000, avgViews: 380000, postFreq: 14,
    email: '', otherContacts: [],
    bio: 'AI art curation. The best AI-generated images from around the world.', verified: false,
    tags: ['ai art', 'ai image', 'generative art', 'ai generated'],
    profileUrl: 'https://x.com/aboroArtCurator',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aboroArtCurator',
  },
  {
    id: 'x_011', platform: 'x', username: 'aboroComfyUI', displayName: 'ComfyUI Tutorials',
    followers: 185000, avgViews: 150000, postFreq: 10,
    email: '', otherContacts: [],
    bio: 'ComfyUI workflows & tutorials. Master AI image generation with node-based workflows.', verified: false,
    tags: ['comfyui', 'stable diffusion', 'ai image', 'ai workflow'],
    profileUrl: 'https://x.com/aboroComfyUI',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aboroComfyUI',
  },
  {
    id: 'x_012', platform: 'x', username: 'aboroMusicAI', displayName: 'AI Music Daily',
    followers: 145000, avgViews: 95000, postFreq: 8,
    email: '', otherContacts: [],
    bio: 'AI music generation. Suno, Udio, and the future of music with AI.', verified: false,
    tags: ['ai music', 'suno', 'udio', 'ai generated music'],
    profileUrl: 'https://x.com/aboroMusicAI',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aboroMusicAI',
  },
  {
    id: 'x_013', platform: 'x', username: 'aboroPromptMaster', displayName: 'Prompt Master',
    followers: 420000, avgViews: 350000, postFreq: 20,
    email: '', otherContacts: [],
    bio: 'ChatGPT & Claude prompts, tips, and use cases. Level up your AI assistant game.', verified: false,
    tags: ['chatgpt', 'claude', 'ai prompts', 'ai productivity'],
    profileUrl: 'https://x.com/aboroPromptMaster',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aboroPromptMaster',
  },
  {
    id: 'x_014', platform: 'x', username: 'aboroKlingAI', displayName: 'Kling AI Videos',
    followers: 125000, avgViews: 98000, postFreq: 12,
    email: '', otherContacts: [],
    bio: 'Kling AI video generation showcase. The best AI videos made with Kling.', verified: false,
    tags: ['kling', 'ai video', 'text to video', 'ai generated video'],
    profileUrl: 'https://x.com/aboroKlingAI',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aboroKlingAI',
  },
  {
    id: 'x_015', platform: 'x', username: 'aboroCodeAI', displayName: 'AI Code Lab',
    followers: 230000, avgViews: 180000, postFreq: 14,
    email: '', otherContacts: [],
    bio: 'AI coding assistants. Cursor, Copilot, Devin, and the future of programming with AI.', verified: false,
    tags: ['ai', 'ai coding', 'cursor', 'copilot', 'programming'],
    profileUrl: 'https://x.com/aboroCodeAI',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aboroCodeAI',
  },
];
